/* Generated By:JavaCC: Do not edit this line. AspParseConstants.java */
package org.aspcloud.engine.asp.parse;

public interface AspParseConstants {

  int EOF = 0;
  int INCLUDE = 1;
  int HTML = 2;
  int LANGUAGEDEF = 3;
  int OUTPUTSCRIPT = 4;
  int ASPSCRIPT = 5;
  int SERVERSCRIPT = 6;
  int NOTSTARTASP = 7;
  int NOTENDASP = 8;
  int STARTASP = 9;
  int ENDASP = 10;
  int WS = 11;
  int FILENAME = 12;
  int QUOTEDFILENAME = 13;
  int PARAM = 14;
  int LANGUAGEPARAM = 15;
  int RUNATPARAM = 16;
  int SCRIPTSTART = 17;
  int NOTSCRIPTEND = 18;
  int SCRIPTEND = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<INCLUDE>",
    "<HTML>",
    "<LANGUAGEDEF>",
    "<OUTPUTSCRIPT>",
    "<ASPSCRIPT>",
    "<SERVERSCRIPT>",
    "<NOTSTARTASP>",
    "<NOTENDASP>",
    "<STARTASP>",
    "<ENDASP>",
    "<WS>",
    "<FILENAME>",
    "<QUOTEDFILENAME>",
    "<PARAM>",
    "<LANGUAGEPARAM>",
    "<RUNATPARAM>",
    "<SCRIPTSTART>",
    "<NOTSCRIPTEND>",
    "\"</SCRIPT>\"",
  };

}
