/* Generated By:JavaCC: Do not edit this line. AspParseTokenManager.java */
package org.aspcloud.engine.asp.parse;
import org.aspcloud.engine.asp.*;

public class AspParseTokenManager implements AspParseConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(6, 0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 205;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if ((0xefffffffffffffffL & l) != 0L)
                  {
                     if (kind > 2)
                        kind = 2;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 60)
                     jjCheckNAddStates(3, 10);
                  if (curChar == 60)
                     jjCheckNAddStates(11, 14);
                  break;
               case 0:
                  if ((0xefffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(0, 2);
                  break;
               case 1:
                  if (curChar == 60)
                     jjCheckNAdd(2);
                  break;
               case 2:
                  if ((0xffff7fddffffffffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(0, 2);
                  break;
               case 3:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(0, 2);
                  break;
               case 5:
                  if (curChar == 60)
                     jjCheckNAdd(3);
                  break;
               case 7:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(8, 39);
                  break;
               case 8:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(8, 39);
                  break;
               case 10:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(15, 17);
                  break;
               case 12:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(18, 19);
                  break;
               case 13:
                  if (curChar == 61)
                     jjCheckNAddStates(20, 23);
                  break;
               case 14:
                  if ((0xbfffffdeffffffffL & l) != 0L)
                     jjCheckNAddStates(24, 26);
                  break;
               case 15:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(15, 18);
                  break;
               case 16:
                  if (curChar == 62 && kind > 1)
                     kind = 1;
                  break;
               case 17:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 20:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 21:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(15, 18);
                  break;
               case 22:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddStates(27, 31);
                  break;
               case 39:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 41:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 33 && kind > 2)
                     kind = 2;
                  break;
               case 44:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 60)
                     jjCheckNAddStates(3, 10);
                  break;
               case 46:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(47, 48);
                  break;
               case 47:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(47, 48);
                  break;
               case 49:
                  if ((0xffffffdfffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(49, 50);
                  break;
               case 50:
                  if (curChar == 37)
                     jjAddStates(32, 33);
                  break;
               case 51:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(49, 50);
                  break;
               case 52:
                  if (curChar == 62 && kind > 3)
                     kind = 3;
                  break;
               case 53:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(54, 55);
                  break;
               case 54:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(54, 55);
                  break;
               case 55:
                  if (curChar == 61)
                     jjCheckNAddTwoStates(56, 57);
                  break;
               case 56:
                  if ((0xffffffdfffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(56, 57);
                  break;
               case 57:
                  if (curChar == 37)
                     jjAddStates(34, 35);
                  break;
               case 58:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(56, 57);
                  break;
               case 59:
                  if (curChar == 62 && kind > 4)
                     kind = 4;
                  break;
               case 60:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(61, 62);
                  break;
               case 61:
                  if ((0xffffffdfffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(61, 62);
                  break;
               case 62:
                  if (curChar == 37)
                     jjAddStates(36, 37);
                  break;
               case 63:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(61, 62);
                  break;
               case 64:
                  if (curChar == 62 && kind > 5)
                     kind = 5;
                  break;
               case 65:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(65, 158);
                  break;
               case 67:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(38, 39);
                  break;
               case 69:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(40, 41);
                  break;
               case 70:
                  if (curChar == 61)
                     jjAddStates(42, 43);
                  break;
               case 71:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(72, 73);
                  break;
               case 72:
                  if ((0xbffffffeffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(72, 73);
                  break;
               case 73:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(73, 143);
                  break;
               case 75:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(44, 45);
                  break;
               case 76:
                  if (curChar == 61)
                     jjAddStates(46, 47);
                  break;
               case 78:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 79:
                  if (curChar == 62)
                     jjCheckNAddStates(48, 50);
                  break;
               case 80:
                  if ((0xefffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 81:
                  if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 83:
                  if (curChar == 60)
                     jjAddStates(51, 58);
                  break;
               case 84:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
               case 87:
               case 90:
               case 94:
               case 99:
               case 105:
                  jjCheckNAddStates(48, 50);
                  break;
               case 88:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 92:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 97:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 103:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 110:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 112:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 118:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 126:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 132:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 139:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 144:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(145, 146);
                  break;
               case 145:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(145, 146);
                  break;
               case 146:
                  if (curChar == 34)
                     jjCheckNAdd(73);
                  break;
               case 159:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(159, 204);
                  break;
               case 161:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(59, 60);
                  break;
               case 163:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(61, 62);
                  break;
               case 164:
                  if (curChar == 61)
                     jjAddStates(63, 64);
                  break;
               case 166:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(166, 182);
                  break;
               case 168:
                  if ((0x100002600L & l) != 0L)
                     jjAddStates(65, 66);
                  break;
               case 169:
                  if (curChar == 61)
                     jjAddStates(67, 68);
                  break;
               case 170:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(69, 71);
                  break;
               case 171:
                  if ((0xbffffffeffffffffL & l) != 0L)
                     jjCheckNAddStates(69, 71);
                  break;
               case 172:
                  if ((0x100002600L & l) != 0L)
                     jjCheckNAddTwoStates(172, 79);
                  break;
               case 173:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(174, 175);
                  break;
               case 174:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(174, 175);
                  break;
               case 175:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(172, 79);
                  break;
               case 188:
                  if (curChar == 34)
                     jjCheckNAdd(166);
                  break;
               case 195:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 6:
               case 0:
               case 2:
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(0, 2);
                  break;
               case 4:
                  if ((0xfff7fffffff7ffffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(0, 2);
                  break;
               case 9:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(15, 17);
                  break;
               case 11:
                  if ((0x100000001000L & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 14:
                  jjAddStates(24, 26);
                  break;
               case 20:
                  jjAddStates(72, 73);
                  break;
               case 23:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 24:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 30:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 34:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 43:
                  if ((0x8000000080000L & l) != 0L && kind > 2)
                     kind = 2;
                  break;
               case 48:
                  if (curChar == 64)
                     jjCheckNAddTwoStates(49, 50);
                  break;
               case 49:
               case 51:
                  jjCheckNAddTwoStates(49, 50);
                  break;
               case 56:
               case 58:
                  jjCheckNAddTwoStates(56, 57);
                  break;
               case 61:
               case 63:
                  jjCheckNAddTwoStates(61, 62);
                  break;
               case 66:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 68:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(40, 41);
                  break;
               case 71:
               case 72:
                  jjCheckNAddTwoStates(72, 73);
                  break;
               case 74:
                  if ((0x10000000100000L & l) != 0L)
                     jjAddStates(44, 45);
                  break;
               case 77:
                  if ((0x4000000040000L & l) != 0L)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 80:
               case 82:
               case 112:
                  jjCheckNAddStates(48, 50);
                  break;
               case 85:
                  if ((0xfff7fffffff7ffffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 86:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if ((0xfffffff7fffffff7L & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 89:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if ((0xfffbfffffffbffffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 91:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 93:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if ((0xfffffdfffffffdffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 95:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 96:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 98:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 99:
                  if ((0xfffefffffffeffffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 100:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 101:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 104:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 105:
                  if ((0xffefffffffefffffL & l) != 0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 106:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 107:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 111:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 113:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 114:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 120:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 127:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 128:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 133:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 140:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 141:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 145:
                  jjAddStates(74, 75);
                  break;
               case 147:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 148:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 155:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 160:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 162:
                  if ((0x10000000100000L & l) != 0L)
                     jjAddStates(61, 62);
                  break;
               case 165:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 167:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(65, 66);
                  break;
               case 170:
               case 171:
                  jjCheckNAddStates(69, 71);
                  break;
               case 174:
                  jjAddStates(76, 77);
                  break;
               case 176:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 177:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 182:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 184:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 189:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 193:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 194:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 196:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 197:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 199:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 200:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 201:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 6:
               case 0:
               case 2:
               case 4:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAddStates(0, 2);
                  break;
               case 14:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(24, 26);
                  break;
               case 20:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(72, 73);
                  break;
               case 49:
               case 51:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(49, 50);
                  break;
               case 56:
               case 58:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(56, 57);
                  break;
               case 61:
               case 63:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(61, 62);
                  break;
               case 71:
               case 72:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(72, 73);
                  break;
               case 80:
               case 82:
               case 85:
               case 87:
               case 90:
               case 94:
               case 99:
               case 105:
               case 112:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(48, 50);
                  break;
               case 145:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(74, 75);
                  break;
               case 170:
               case 171:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(69, 71);
                  break;
               case 174:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(76, 77);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 205 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   0, 1, 5, 2, 46, 53, 60, 65, 158, 159, 204, 41, 42, 44, 3, 10, 
   28, 32, 12, 13, 14, 19, 18, 22, 14, 15, 18, 14, 19, 15, 18, 22, 
   51, 52, 58, 59, 63, 64, 67, 153, 69, 70, 71, 144, 75, 76, 131, 139, 
   80, 81, 83, 84, 88, 92, 97, 103, 110, 118, 126, 161, 199, 163, 164, 187, 
   195, 168, 169, 170, 173, 171, 172, 79, 20, 21, 145, 146, 174, 175, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[205];
private final int[] jjstateSet = new int[410];
protected char curChar;
public AspParseTokenManager(SimpleCharStream stream)
{
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public AspParseTokenManager(SimpleCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 205; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
