/* Generated By:JavaCC: Do not edit this line. VBScriptConstants.java */
package org.aspcloud.engine.asp.parse;

public interface VBScriptConstants {

  int EOF = 0;
  int NL = 1;
  int HTML = 2;
  int OUTPUT = 3;
  int SEMI = 4;
  int CONCAT = 5;
  int DOT = 6;
  int EXP = 7;
  int LPAREN = 8;
  int MINUS = 9;
  int PLUS = 10;
  int EQ = 11;
  int GT = 12;
  int LT = 13;
  int GE = 14;
  int LE = 15;
  int NE = 16;
  int RPAREN = 17;
  int COMMA = 18;
  int INTDIV = 19;
  int DIV = 20;
  int MULT = 21;
  int STRING = 22;
  int REMARK = 23;
  int INTEGER = 24;
  int DOUBLE = 25;
  int HEXSEQUENCE = 26;
  int EXITFUNCTION = 27;
  int EXITSUB = 28;
  int EXITDO = 29;
  int EXITFOR = 30;
  int GOTO = 31;
  int ONERROR = 32;
  int RESUMENEXT = 33;
  int OPTIONEXPLICIT = 34;
  int IF = 35;
  int THEN = 36;
  int ELSE = 37;
  int ELSEIF = 38;
  int ENDIF = 39;
  int DIM = 40;
  int REDIM = 41;
  int PRESERVE = 42;
  int SET = 43;
  int IS = 44;
  int MOD = 45;
  int NOT = 46;
  int AND = 47;
  int OR = 48;
  int XOR = 49;
  int EQV = 50;
  int IMP = 51;
  int FOR = 52;
  int TO = 53;
  int STEP = 54;
  int NEXT = 55;
  int IN = 56;
  int EACH = 57;
  int CALL = 58;
  int SUB = 59;
  int FUNCTION = 60;
  int ENDSUB = 61;
  int ENDFUNCTION = 62;
  int BYVAL = 63;
  int BYREF = 64;
  int DO = 65;
  int UNTIL = 66;
  int LOOP = 67;
  int WHILE = 68;
  int WEND = 69;
  int CONST = 70;
  int PUBLIC = 71;
  int PRIVATE = 72;
  int SELECTCASE = 73;
  int ENDSELECT = 74;
  int CASE = 75;
  int CASEELSE = 76;
  int IDENTIFIER = 77;
  int WS = 78;
  int COMMENT = 79;
  int CONTINUE = 80;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<NL>",
    "\"<%%>\"",
    "\"<%=%>\"",
    "\":\"",
    "\"&\"",
    "<DOT>",
    "\"^\"",
    "\"(\"",
    "\"-\"",
    "\"+\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\")\"",
    "\",\"",
    "\"\\\\\"",
    "\"/\"",
    "\"*\"",
    "<STRING>",
    "<REMARK>",
    "<INTEGER>",
    "<DOUBLE>",
    "<HEXSEQUENCE>",
    "<EXITFUNCTION>",
    "<EXITSUB>",
    "<EXITDO>",
    "<EXITFOR>",
    "\"GOTO\"",
    "<ONERROR>",
    "<RESUMENEXT>",
    "<OPTIONEXPLICIT>",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"ELSEIF\"",
    "<ENDIF>",
    "\"DIM\"",
    "\"REDIM\"",
    "\"PRESERVE\"",
    "\"SET\"",
    "\"IS\"",
    "\"MOD\"",
    "\"NOT\"",
    "\"AND\"",
    "\"OR\"",
    "\"XOR\"",
    "\"EQV\"",
    "\"IMP\"",
    "\"FOR\"",
    "\"TO\"",
    "\"STEP\"",
    "\"NEXT\"",
    "\"IN\"",
    "\"EACH\"",
    "\"CALL\"",
    "\"SUB\"",
    "\"FUNCTION\"",
    "<ENDSUB>",
    "<ENDFUNCTION>",
    "\"BYVAL\"",
    "\"BYREF\"",
    "\"DO\"",
    "\"UNTIL\"",
    "\"LOOP\"",
    "\"WHILE\"",
    "\"WEND\"",
    "\"CONST\"",
    "\"PUBLIC\"",
    "\"PRIVATE\"",
    "<SELECTCASE>",
    "<ENDSELECT>",
    "\"CASE\"",
    "<CASEELSE>",
    "<IDENTIFIER>",
    "<WS>",
    "<COMMENT>",
    "<CONTINUE>",
    "\" \"",
    "\"\\t\"",
  };

}
